// Template Engine - 문서 HTML 생성

import { DOCUMENT_CSS, PAGE_LIMITS, type DocumentType, type DocumentMode } from './documentStyles';
import type { 
  DocumentTemplateData, 
  PITemplateData, 
  ContractTemplateData,
  SKUData,
  ProjectData,
  BuyerData,
  TradeData,
  WorkspaceData,
} from './documentTypes';
import { format } from 'date-fns';

// 헬퍼 함수: 통화 포맷
function formatCurrency(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency || 'USD',
    minimumFractionDigits: 2,
  }).format(amount);
}

// 헬퍼 함수: 공통 헤더
function renderHeader(title: string, subtitle: string, docNumber: string, date: string, meta?: string, logoUrl?: string): string {
  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="Logo" style="width:34px;height:34px;border-radius:12px;object-fit:contain;" />`
    : `<div class="logo"></div>`;
  return `
    <div class="header">
      <div class="brandmark">
        ${logoHtml}
        <div>
          <div class="doctitle">${title}</div>
          <div class="small">${subtitle}</div>
        </div>
      </div>
      <div class="docmeta">
        <div><strong>${docNumber}</strong></div>
        <div><strong>Date</strong> ${date}</div>
        ${meta ? `<div class="small">${meta}</div>` : ''}
      </div>
    </div>
  `;
}

// 헬퍼 함수: 공통 푸터
function renderFooter(leftText: string, pageNum: number): string {
  return `<div class="footer"><span>${leftText}</span><span>Page ${pageNum}</span></div>`;
}

// 헬퍼 함수: 초안 배너
function renderDraftBanner(): string {
  return `
    <div class="draft-banner">
      ⚠️ 이 문서는 <strong>협상/검토용 초안</strong>입니다. 최종 제출 전 확인이 필요합니다.
    </div>
  `;
}

// ==================== PI 템플릿 ====================
function renderPI(data: PITemplateData, mode: DocumentMode): string {
  const { workspace, project, skus, buyer, trade } = data;
  const currency = trade.currency || 'USD';
  const subtotal = skus.reduce((sum, sku) => sum + sku.amount, 0);
  const total = subtotal + (trade.shippingCost || 0);
  
  const piNumber = data.piNumber || `PI-${format(new Date(), 'yyyyMMdd')}-001`;
  const dateStr = data.date || format(new Date(), 'yyyy-MM-dd');
  const logoUrl = workspace.logoUrl || '';
  const stampImageUrl = workspace.stampImageUrl || '';
  const signatureImageUrl = workspace.signatureImageUrl || '';

  let html = `
    <style>${DOCUMENT_CSS}</style>
    <div class="doc-wrap">
      <!-- Page 1 -->
      <section class="page" data-page="1">
        ${renderHeader('PROFORMA INVOICE (PI)', 'Draft generated by Export Ops AI', piNumber, dateStr, `Target: ${project.countries.join(', ')} · Channel: ${project.channel}`, logoUrl)}
        
        <div class="page-inner">
          ${renderDraftBanner()}
          
          <div class="grid-2">
            <div class="card" data-section-id="pi_seller">
              <div class="h2">Seller (판매자)</div>
              <table class="table">
                <tr><th>Company</th><td><strong>${workspace.companyName}</strong></td></tr>
                <tr><th>Brand</th><td>${workspace.brandName || workspace.companyName}</td></tr>
                <tr><th>Address</th><td>${workspace.address || '-'}</td></tr>
                <tr><th>Contact</th><td>${workspace.contactPhone || '-'}</td></tr>
                <tr><th>Email</th><td>${workspace.contactEmail || '-'}</td></tr>
              </table>
            </div>
            <div class="card" data-section-id="pi_buyer">
              <div class="h2">Buyer (바이어)</div>
              ${buyer ? `
                <table class="table">
                  <tr><th>Company</th><td><strong>${buyer.companyName}</strong></td></tr>
                  <tr><th>Contact</th><td>${buyer.contactName || '-'}</td></tr>
                  <tr><th>Country</th><td>${buyer.country}</td></tr>
                  <tr><th>Email</th><td>${buyer.contactEmail || '-'}</td></tr>
                  <tr><th>Ship to</th><td>${buyer.address || '-'}</td></tr>
                </table>
              ` : `
                <div class="callout warn">
                  <strong>바이어 정보 미입력</strong><br/>
                  발송 전 바이어 정보를 입력해주세요.
                </div>
              `}
            </div>
          </div>

          <div class="hr"></div>

          <div class="card" data-section-id="pi_items">
            <div class="h2">Item Details (품목)</div>
            <table class="table">
              <tr>
                <th>No</th><th>Product</th><th>SKU</th><th>HS Code</th><th>Qty</th><th>Unit Price</th><th>Amount</th>
              </tr>
              ${skus.map((sku, i) => `
                <tr>
                  <td>${i + 1}</td>
                  <td><strong>${sku.productName}</strong><div class="small">${sku.spec || ''}</div></td>
                  <td>${sku.sku}</td>
                  <td>${sku.hsCode || '-'}</td>
                  <td>${sku.qty.toLocaleString()}</td>
                  <td>${formatCurrency(sku.unitPrice, currency)}</td>
                  <td><strong>${formatCurrency(sku.amount, currency)}</strong></td>
                </tr>
              `).join('')}
            </table>

            <div class="grid-2" style="margin-top:12px">
              <div class="small" data-section-id="pi_notes">
                <strong>Notes</strong><br/>
                - Prices are in ${currency}.<br/>
                - This PI is a draft for negotiation and confirmation.<br/>
                - Final documents will be issued after terms confirmation.
              </div>
              <div>
                <table class="table" data-section-id="pi_totals">
                  <tr><th>Subtotal</th><td style="text-align:right"><strong>${formatCurrency(subtotal, currency)}</strong></td></tr>
                  <tr><th>Shipping/Insurance</th><td style="text-align:right">${formatCurrency(trade.shippingCost || 0, currency)}</td></tr>
                  <tr><th>Total</th><td style="text-align:right"><strong>${formatCurrency(total, currency)}</strong></td></tr>
                </table>
              </div>
            </div>
          </div>

          <div class="hr"></div>

          <div class="grid-2">
            <div class="card" data-section-id="pi_terms">
              <div class="h2">Trade Terms (거래 조건)</div>
              <table class="table">
                <tr><th>Incoterms</th><td>${trade.incoterms}</td></tr>
                <tr><th>Payment</th><td>${trade.paymentTerms}</td></tr>
                <tr><th>Lead Time</th><td>${trade.leadTime}</td></tr>
                <tr><th>MOQ</th><td>${trade.moq?.toLocaleString()}</td></tr>
                <tr><th>Validity</th><td>${trade.validityDays} days</td></tr>
              </table>
            </div>
            <div class="card" data-section-id="pi_bank">
              <div class="h2">Bank Details (결제 정보)</div>
              <table class="table">
                <tr><th>Bank</th><td>${workspace.bankName || '-'}</td></tr>
                <tr><th>Account Name</th><td>${workspace.bankAccountName || workspace.companyName}</td></tr>
                <tr><th>Account No.</th><td>${workspace.bankAccountNo || '-'}</td></tr>
                <tr><th>SWIFT</th><td>${workspace.bankSwift || '-'}</td></tr>
              </table>
              <div class="small">* 실제 발행 전 고객이 은행 정보를 확인해야 합니다.</div>
            </div>
          </div>
        </div>
        ${renderFooter(workspace.companyName, 1)}
      </section>
  `;

  // Page 2 (detailed only)
  if (mode === 'detailed') {
    html += `
      <!-- Page 2 -->
      <section class="page" data-page="2" data-include="detailed">
        ${renderHeader('PI Appendix', 'Packing / Documents / Checklist', piNumber, dateStr)}
        <div class="page-inner">
          <div class="grid-2">
            <div class="card" data-section-id="pi_packing">
              <div class="h2">Packing (포장)</div>
              <table class="table">
                <tr><th>Carton spec</th><td>${data.docCI || 'TBD'}</td></tr>
                <tr><th>Gross/Net</th><td>TBD</td></tr>
                <tr><th>Cartons</th><td>TBD</td></tr>
                <tr><th>Pallet</th><td>TBD</td></tr>
              </table>
            </div>
            <div class="card" data-section-id="pi_docs">
              <div class="h2">Documents (서류)</div>
              <table class="table">
                <tr><th>Commercial Invoice</th><td>${data.docCI || 'To be issued'}</td></tr>
                <tr><th>Packing List</th><td>${data.docPL || 'To be issued'}</td></tr>
                <tr><th>COO</th><td>${data.docCOO || 'If required'}</td></tr>
                <tr><th>Other</th><td>${data.docOther || '-'}</td></tr>
              </table>
            </div>
          </div>
          <div class="hr"></div>
          <div class="callout" data-section-id="pi_signature">
            <strong>Signature (서명)</strong><br/><br/>
            <div style="display:flex;gap:40px;align-items:flex-end;">
              <div>
                <div class="small">Seller Authorized Signature:</div>
                <div style="margin-top:8px;min-height:60px;display:flex;gap:12px;align-items:center;">
                  ${signatureImageUrl ? `<img src="${signatureImageUrl}" alt="Signature" style="max-height:50px;max-width:150px;object-fit:contain;" />` : '<div style="border-bottom:1px solid #999;width:150px;height:50px;"></div>'}
                  ${stampImageUrl ? `<img src="${stampImageUrl}" alt="Stamp" style="max-height:60px;max-width:60px;object-fit:contain;" />` : ''}
                </div>
                ${workspace.ceoName ? `<div class="small" style="margin-top:6px;">${workspace.ceoName} · ${workspace.companyName}</div>` : ''}
              </div>
              <div>
                <div class="small">Date: ${dateStr}</div>
              </div>
            </div>
          </div>
        </div>
        ${renderFooter(workspace.companyName, 2)}
      </section>
    `;
  }

  html += '</div>';
  return html;
}

// ==================== Contract 템플릿 ====================
function renderContract(data: ContractTemplateData, mode: DocumentMode): string {
  const { workspace, project, skus, buyer, trade } = data;
  const currency = trade.currency || 'USD';
  const subtotal = skus.reduce((sum, sku) => sum + sku.amount, 0);
  const total = subtotal;
  
  const contractNumber = data.contractNumber || `SC-${format(new Date(), 'yyyyMMdd')}-001`;
  const dateStr = data.date || format(new Date(), 'yyyy-MM-dd');
  const governingLaw = data.governingLaw || 'Republic of Korea';
  const logoUrl = workspace.logoUrl || '';
  const stampImageUrl = workspace.stampImageUrl || '';
  const signatureImageUrl = workspace.signatureImageUrl || '';

  let html = `
    <style>${DOCUMENT_CSS}</style>
    <div class="doc-wrap">
      <!-- Page 1: Cover & Parties -->
      <section class="page" data-page="1">
        ${renderHeader('SALES CONTRACT (Draft)', 'Generated by Export Ops AI · Customer confirmation required', contractNumber, dateStr, `Stage: ${project.tradeStage} · Target: ${project.countries.join(', ')}`, logoUrl)}
        
        <div class="page-inner">
          <div class="callout" data-section-id="contract_disclaimer">
            <strong>중요 안내</strong><br/>
            본 문서는 "협상/검토용 초안"입니다. 최종 서명 전, 당사자 확인 및 필요 시 법무/무역 전문가 검토가 필요합니다.
          </div>

          <div class="hr"></div>

          <div class="grid-2">
            <div class="card" data-section-id="contract_seller">
              <div class="h2">Seller (판매자)</div>
              <table class="table">
                <tr><th>Company</th><td><strong>${workspace.companyName}</strong></td></tr>
                <tr><th>Address</th><td>${workspace.address || '-'}</td></tr>
                <tr><th>Representative</th><td>${data.sellerRep || '-'}</td></tr>
                <tr><th>Email</th><td>${workspace.contactEmail || '-'}</td></tr>
              </table>
            </div>
            <div class="card" data-section-id="contract_buyer">
              <div class="h2">Buyer (구매자)</div>
              ${buyer ? `
                <table class="table">
                  <tr><th>Company</th><td><strong>${buyer.companyName}</strong></td></tr>
                  <tr><th>Address</th><td>${buyer.address || '-'}</td></tr>
                  <tr><th>Representative</th><td>${data.buyerRep || buyer.contactName || '-'}</td></tr>
                  <tr><th>Email</th><td>${buyer.contactEmail || '-'}</td></tr>
                </table>
              ` : `
                <div class="callout warn">
                  <strong>바이어 정보 미입력</strong><br/>
                  계약서 작성 전 바이어 정보를 입력해주세요.
                </div>
              `}
            </div>
          </div>

          <div class="hr"></div>

          <div class="card" data-section-id="contract_definitions">
            <div class="h2">1. Definitions (정의)</div>
            <p class="p">${data.definitionsText || '"Seller" refers to the party selling the Products. "Buyer" refers to the party purchasing the Products. "Products" refers to the goods listed in Schedule A. "Contract" refers to this Sales Contract including all schedules and amendments.'}</p>
          </div>
        </div>
        ${renderFooter(`${workspace.companyName} · ${buyer?.companyName || 'Buyer TBD'}`, 1)}
      </section>

      <!-- Page 2: Products & Price (Schedule A) -->
      <section class="page" data-page="2">
        ${renderHeader('2. Products & Price', 'Schedule A', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_scheduleA">
          <div class="h2">Schedule A — Product List (제품/가격)</div>
          <table class="table">
            <tr>
              <th>No</th><th>Product</th><th>SKU</th><th>Spec</th><th>Qty</th><th>Unit Price</th><th>Amount</th>
            </tr>
            ${skus.map((sku, i) => `
              <tr>
                <td>${i + 1}</td>
                <td><strong>${sku.productName}</strong><div class="small">${sku.category || ''}</div></td>
                <td>${sku.sku}</td>
                <td>${sku.spec || '-'}</td>
                <td>${sku.qty.toLocaleString()}</td>
                <td>${formatCurrency(sku.unitPrice, currency)}</td>
                <td><strong>${formatCurrency(sku.amount, currency)}</strong></td>
              </tr>
            `).join('')}
          </table>

          <div class="grid-2" style="margin-top:12px">
            <div class="small">
              <strong>Currency</strong>: ${currency}<br/>
              <strong>Price validity</strong>: ${trade.validityDays} days<br/>
              <strong>MOQ</strong>: ${trade.moq?.toLocaleString()}
            </div>
            <div>
              <table class="table">
                <tr><th>Subtotal</th><td style="text-align:right"><strong>${formatCurrency(subtotal, currency)}</strong></td></tr>
                <tr><th>Other costs</th><td style="text-align:right">${formatCurrency(0, currency)}</td></tr>
                <tr><th>Total</th><td style="text-align:right"><strong>${formatCurrency(total, currency)}</strong></td></tr>
              </table>
            </div>
          </div>

          <div class="callout" style="margin-top:14px" data-section-id="contract_product_notes">
            <strong>제품 관련 특이사항(초안)</strong><br/>
            ${data.productSpecialNotes || 'Products are subject to availability. Specifications may vary slightly between production batches.'}
          </div>
        </div>
        ${renderFooter('Schedule A', 2)}
      </section>

      <!-- Page 3: Delivery & Incoterms -->
      <section class="page" data-page="3">
        ${renderHeader('3. Delivery', 'Shipping & Incoterms', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_delivery">
          <table class="table">
            <tr><th>Incoterms</th><td>${trade.incoterms}</td></tr>
            <tr><th>Port / Destination</th><td>${trade.destination || 'TBD'}</td></tr>
            <tr><th>Lead Time</th><td>${trade.leadTime}</td></tr>
            <tr><th>Partial shipment</th><td>${trade.partialShipment || 'Allowed'}</td></tr>
            <tr><th>Insurance</th><td>${trade.insurance || 'As per Incoterms'}</td></tr>
          </table>
          <div class="hr"></div>
          <div class="card" data-section-id="contract_packing">
            <div class="h2">Packing (포장)</div>
            <p class="p">${data.packingText || 'Standard export packing suitable for ocean/air freight. Individual product packaging with outer carton protection.'}</p>
          </div>
        </div>
        ${renderFooter('Delivery', 3)}
      </section>

      <!-- Page 4: Payment -->
      <section class="page" data-page="4">
        ${renderHeader('4. Payment', 'How you pay', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_payment">
          <table class="table">
            <tr><th>Payment Terms</th><td>${trade.paymentTerms}</td></tr>
            <tr><th>Bank</th><td>${workspace.bankName || '-'}</td></tr>
            <tr><th>Account Name</th><td>${workspace.bankAccountName || workspace.companyName}</td></tr>
            <tr><th>Account No.</th><td>${workspace.bankAccountNo || '-'}</td></tr>
            <tr><th>SWIFT</th><td>${workspace.bankSwift || '-'}</td></tr>
          </table>
          <div class="callout" style="margin-top:14px" data-section-id="payment_risk_note">
            <strong>리스크 팁</strong><br/>
            선금/잔금 구조, L/C 또는 에스크로 필요 여부는 거래 규모/신뢰도에 따라 조정하세요.
          </div>
        </div>
        ${renderFooter('Payment', 4)}
      </section>

      <!-- Page 5: Inspection & Claims (summary include) -->
      <section class="page" data-page="5">
        ${renderHeader('5. Inspection & Claims', 'Quality / Returns', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_claims">
          <table class="table">
            <tr><th>Inspection</th><td>${data.inspectionTerms || 'Buyer shall inspect goods within 14 days of receipt.'}</td></tr>
            <tr><th>Defects & Claims</th><td>${data.claimsTerms || 'Claims for defects must be notified in writing within 30 days.'}</td></tr>
            <tr><th>Return/Refund</th><td>${data.returnTerms || 'Subject to mutual agreement. Shipping costs for returns borne by claiming party.'}</td></tr>
            <tr><th>Warranty</th><td>${data.warrantyTerms || 'Products warranted for 12 months from delivery against manufacturing defects.'}</td></tr>
          </table>
        </div>
        ${renderFooter('Claims', 5)}
      </section>
  `;

  // Detailed mode: Pages 6-10
  if (mode === 'detailed') {
    html += `
      <!-- Page 6: Compliance -->
      <section class="page" data-page="6" data-include="detailed">
        ${renderHeader('6. Compliance', 'Regulatory responsibility', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_compliance">
          <p class="p">${data.complianceClause || 'Seller warrants that Products comply with applicable laws of the country of origin. Buyer is responsible for compliance with import regulations and requirements of the destination country.'}</p>
          <div class="hr"></div>
          <div class="callout">
            <strong>참고</strong><br/>
            "수출 준비 요약(Compliance Snapshot)"에서 체크리스트를 만들고, 계약서 조항과 일치시키세요.
          </div>
        </div>
        ${renderFooter('Compliance', 6)}
      </section>

      <!-- Page 7: IP & Confidentiality -->
      <section class="page" data-page="7" data-include="detailed">
        ${renderHeader('7. IP & Confidentiality', 'Brand / Formula', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_ip_conf">
          <table class="table">
            <tr><th>IP</th><td>${data.ipClause || 'All intellectual property rights in the Products, including trademarks and formulations, remain with the Seller.'}</td></tr>
            <tr><th>Confidentiality</th><td>${data.confClause || 'Both parties agree to keep confidential any proprietary information exchanged during the course of this agreement.'}</td></tr>
          </table>
        </div>
        ${renderFooter('IP/Confidentiality', 7)}
      </section>

      <!-- Page 8: Force Majeure -->
      <section class="page" data-page="8" data-include="detailed">
        ${renderHeader('8. Force Majeure', 'Unexpected events', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_force">
          <p class="p">${data.forceMajeureClause || 'Neither party shall be liable for failure to perform obligations due to circumstances beyond reasonable control, including natural disasters, war, government actions, or pandemics. The affected party shall notify the other party promptly and both parties shall discuss in good faith how to proceed.'}</p>
        </div>
        ${renderFooter('Force Majeure', 8)}
      </section>

      <!-- Page 9: Governing Law & Dispute -->
      <section class="page" data-page="9" data-include="detailed">
        ${renderHeader('9. Governing Law & Dispute', 'Legal', contractNumber, dateStr)}
        <div class="page-inner" data-section-id="contract_law">
          <table class="table">
            <tr><th>Governing law</th><td>${governingLaw}</td></tr>
            <tr><th>Dispute resolution</th><td>${data.disputeClause || 'Any dispute shall first be resolved through good faith negotiation. If unresolved, disputes shall be submitted to arbitration in accordance with the rules of KCAB (Korean Commercial Arbitration Board).'}</td></tr>
          </table>
        </div>
        ${renderFooter('Law', 9)}
      </section>

      <!-- Page 10: Signatures -->
      <section class="page" data-page="10" data-include="detailed">
        ${renderHeader('10. Signatures', 'Execution', contractNumber, dateStr, undefined, logoUrl)}
        <div class="page-inner" data-section-id="contract_sign">
          <div class="grid-2">
            <div class="card">
              <div class="h2">Seller</div>
              <p class="p">${workspace.companyName}</p>
              <div class="hr"></div>
              <div style="min-height:70px;display:flex;gap:12px;align-items:center;margin:10px 0;">
                ${signatureImageUrl ? `<img src="${signatureImageUrl}" alt="Signature" style="max-height:50px;max-width:150px;object-fit:contain;" />` : '<div class="small">Authorized Signature: ____________________</div>'}
                ${stampImageUrl ? `<img src="${stampImageUrl}" alt="Stamp" style="max-height:60px;max-width:60px;object-fit:contain;" />` : ''}
              </div>
              <div class="small">Name/Title: ${workspace.ceoName || '____________________________'}</div>
              <div class="small" style="margin-top:8px">Date: ${dateStr}</div>
            </div>
            <div class="card">
              <div class="h2">Buyer</div>
              <p class="p">${buyer?.companyName || 'Buyer Company Name'}</p>
              <div class="hr"></div>
              <div class="small" style="margin-top:10px">Authorized Signature: ____________________</div>
              <div class="small" style="margin-top:8px">Name/Title: ____________________________</div>
              <div class="small" style="margin-top:8px">Date: _________________________________</div>
            </div>
          </div>
          <div class="callout" style="margin-top:14px">
            <strong>실수 체크</strong><br/>
            서명 전, PI/카탈로그/계약서의 통화·단가·수량·인코텀즈가 모두 동일한지 확인하세요.
          </div>
        </div>
        ${renderFooter('Signatures', 10)}
      </section>
    `;
  }

  html += '</div>';
  return html;
}

// ==================== Brand Deck 템플릿 ====================
function renderBrandDeck(data: DocumentTemplateData, mode: DocumentMode): string {
  const { workspace, project, skus } = data;
  const dateStr = data.date || format(new Date(), 'yyyy-MM-dd');
  const logoUrl = workspace.logoUrl || '';
  
  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="Logo" style="width:80px;height:80px;object-fit:contain;margin-bottom:24px;" />`
    : `<div class="logo" style="width:80px;height:80px;margin-bottom:24px"></div>`;

  let html = `
    <style>${DOCUMENT_CSS}</style>
    <div class="doc-wrap">
      <!-- Page 1: Cover -->
      <section class="page" data-page="1">
        <div class="page-inner" style="display:flex;flex-direction:column;justify-content:center;align-items:center;min-height:900px;text-align:center">
          ${renderDraftBanner()}
          ${logoHtml}
          <h1 class="h1" data-section-id="deck_title">${workspace.companyName}</h1>
          <p class="p" style="font-size:16px;margin-top:8px">${workspace.brandName || 'Premium K-Beauty'}</p>
          <div class="hr" style="width:60px;margin:24px auto"></div>
          <p class="small">Company Introduction · ${dateStr}</p>
          <p class="small">Target: ${project.countries.join(' / ')} · ${project.channel}</p>
        </div>
        ${renderFooter(workspace.companyName, 1)}
      </section>

      <!-- Page 2: Company Overview -->
      <section class="page" data-page="2">
        ${renderHeader('Company Overview', 'Who We Are', '', dateStr)}
        <div class="page-inner" data-section-id="deck_overview">
          <div class="h2">About ${workspace.companyName}</div>
          <p class="p">Korean beauty company specializing in high-quality skincare products. With years of experience in R&D and manufacturing, we deliver innovative formulations that meet global standards.</p>
          
          <div class="kpi" style="margin-top:24px">
            <div class="card">
              <div class="label">Established</div>
              <div class="val">Since 2010</div>
            </div>
            <div class="card">
              <div class="label">Products</div>
              <div class="val">${skus.length}+ SKUs</div>
            </div>
            <div class="card">
              <div class="label">Export Markets</div>
              <div class="val">20+ Countries</div>
            </div>
          </div>

          <div class="hr"></div>
          
          <div class="grid-2">
            <div class="card">
              <div class="h3">Contact</div>
              <p class="small">${workspace.contactEmail || '-'}</p>
              <p class="small">${workspace.contactPhone || '-'}</p>
              <p class="small">${workspace.website || '-'}</p>
            </div>
            <div class="card">
              <div class="h3">Address</div>
              <p class="small">${workspace.address || 'Seoul, South Korea'}</p>
            </div>
          </div>
        </div>
        ${renderFooter(workspace.companyName, 2)}
      </section>

      <!-- Page 3: Product Lines -->
      <section class="page" data-page="3">
        ${renderHeader('Product Portfolio', 'What We Offer', '', dateStr)}
        <div class="page-inner" data-section-id="deck_products">
          <div class="h2">Product Categories</div>
          <div class="grid-3">
            ${skus.slice(0, 6).map(sku => `
              <div class="card">
                <div class="h3">${sku.productName}</div>
                <p class="small">${sku.category || 'Skincare'}</p>
                <p class="small">MOQ: ${sku.moq || workspace.defaultMoq || 500}</p>
              </div>
            `).join('')}
          </div>
          
          <div class="callout" style="margin-top:24px">
            <strong>Key Strengths</strong><br/>
            ✓ Korean R&D Excellence · ✓ FDA/EU Compliant · ✓ OEM/ODM Available · ✓ Private Label Support
          </div>
        </div>
        ${renderFooter(workspace.companyName, 3)}
      </section>
  `;

  // Summary mode: 1 more page (total 4-5)
  html += `
      <!-- Page 4: Trade Terms -->
      <section class="page" data-page="4">
        ${renderHeader('Trade Terms', 'How We Work', '', dateStr)}
        <div class="page-inner" data-section-id="deck_terms">
          <div class="grid-2">
            <div class="card">
              <div class="h2">Default Terms</div>
              <table class="table">
                <tr><th>MOQ</th><td>${workspace.defaultMoq || 500} units</td></tr>
                <tr><th>Lead Time</th><td>${workspace.defaultLeadTime || 20} days</td></tr>
                <tr><th>Incoterms</th><td>${workspace.defaultIncoterms || 'FOB'}</td></tr>
                <tr><th>Payment</th><td>${workspace.defaultPaymentTerms || 'T/T 30/70'}</td></tr>
              </table>
            </div>
            <div class="card">
              <div class="h2">Certifications</div>
              <p class="p">${workspace.certifications?.join(', ') || 'CGMP, ISO 22716, FDA Registration'}</p>
            </div>
          </div>
          
          <div class="hr"></div>
          
          <div class="callout">
            <strong>Next Steps</strong><br/>
            1. Request product samples<br/>
            2. Discuss volume pricing<br/>
            3. Finalize terms and proceed
          </div>
        </div>
        ${renderFooter(workspace.companyName, 4)}
      </section>
  `;

  // Detailed mode: Pages 5-8
  if (mode === 'detailed') {
    html += `
      <!-- Page 5: Brand Story -->
      <section class="page" data-page="5" data-include="detailed">
        ${renderHeader('Brand Story', 'Our Journey', '', dateStr)}
        <div class="page-inner" data-section-id="deck_story">
          <div class="h2">The ${workspace.brandName || workspace.companyName} Story</div>
          <p class="p">Founded with a passion for K-Beauty innovation, we have grown from a small lab to a global supplier. Our commitment to quality and customer satisfaction drives everything we do.</p>
          
          <div class="hr"></div>
          
          <div class="grid-2">
            <div class="card">
              <div class="h3">Mission</div>
              <p class="p">To bring the best of Korean skincare to the world with safe, effective, and innovative products.</p>
            </div>
            <div class="card">
              <div class="h3">Vision</div>
              <p class="p">To be the preferred K-Beauty partner for global distributors and retailers.</p>
            </div>
          </div>
        </div>
        ${renderFooter(workspace.companyName, 5)}
      </section>

      <!-- Page 6: Manufacturing -->
      <section class="page" data-page="6" data-include="detailed">
        ${renderHeader('Manufacturing', 'Quality Assurance', '', dateStr)}
        <div class="page-inner" data-section-id="deck_manufacturing">
          <div class="h2">Our Facilities</div>
          <p class="p">State-of-the-art manufacturing facility with CGMP certification. Equipped with advanced R&D labs and quality control systems.</p>
          
          <div class="kpi" style="margin-top:20px">
            <div class="card">
              <div class="label">Facility Size</div>
              <div class="val">5,000㎡</div>
            </div>
            <div class="card">
              <div class="label">Production Capacity</div>
              <div class="val">500K/month</div>
            </div>
            <div class="card">
              <div class="label">QC Staff</div>
              <div class="val">20+ Experts</div>
            </div>
          </div>
        </div>
        ${renderFooter(workspace.companyName, 6)}
      </section>

      <!-- Page 7: Global Presence -->
      <section class="page" data-page="7" data-include="detailed">
        ${renderHeader('Global Presence', 'Export Markets', '', dateStr)}
        <div class="page-inner" data-section-id="deck_global">
          <div class="h2">We Export To</div>
          <div class="grid-3">
            <div class="card"><div class="h3">🇺🇸 USA</div></div>
            <div class="card"><div class="h3">🇨🇳 China</div></div>
            <div class="card"><div class="h3">🇯🇵 Japan</div></div>
            <div class="card"><div class="h3">🇻🇳 Vietnam</div></div>
            <div class="card"><div class="h3">🇹🇭 Thailand</div></div>
            <div class="card"><div class="h3">🇪🇺 EU</div></div>
          </div>
        </div>
        ${renderFooter(workspace.companyName, 7)}
      </section>

      <!-- Page 8: Contact -->
      <section class="page" data-page="8" data-include="detailed">
        ${renderHeader('Contact Us', 'Get In Touch', '', dateStr)}
        <div class="page-inner" data-section-id="deck_contact" style="text-align:center;padding-top:100px">
          <div class="logo" style="width:60px;height:60px;margin:0 auto 20px"></div>
          <div class="h1">${workspace.companyName}</div>
          <p class="p" style="margin-top:20px">
            ${workspace.contactEmail || 'contact@company.com'}<br/>
            ${workspace.contactPhone || '+82-2-XXX-XXXX'}<br/>
            ${workspace.website || 'www.company.com'}
          </p>
          <div class="hr" style="width:100px;margin:30px auto"></div>
          <p class="small">Ready to partner with us?</p>
        </div>
        ${renderFooter(workspace.companyName, 8)}
      </section>
    `;
  }

  html += '</div>';
  return html;
}

// ==================== Catalog 템플릿 ====================
function renderCatalog(data: DocumentTemplateData, mode: DocumentMode): string {
  const { workspace, project, skus } = data;
  const dateStr = data.date || format(new Date(), 'yyyy-MM-dd');
  const currency = data.trade?.currency || 'USD';
  
  // SKU 제한: detailed 모드에서도 최대 12개
  const displaySkus = skus.slice(0, mode === 'detailed' ? 12 : 4);

  let html = `
    <style>${DOCUMENT_CSS}</style>
    <div class="doc-wrap">
      <!-- Page 1: Cover -->
      <section class="page" data-page="1">
        <div class="page-inner" style="display:flex;flex-direction:column;justify-content:center;align-items:center;min-height:900px;text-align:center">
          ${renderDraftBanner()}
          <div class="logo" style="width:80px;height:80px;margin-bottom:24px"></div>
          <h1 class="h1">Product Catalog</h1>
          <p class="p" style="font-size:16px;margin-top:8px">${workspace.brandName || workspace.companyName}</p>
          <div class="hr" style="width:60px;margin:24px auto"></div>
          <p class="small">${dateStr} · ${displaySkus.length} Products</p>
          <p class="small">For: ${project.countries.join(' / ')}</p>
        </div>
        ${renderFooter(workspace.companyName, 1)}
      </section>

      <!-- Page 2: Lineup Summary -->
      <section class="page" data-page="2">
        ${renderHeader('Product Lineup', 'Overview', '', dateStr)}
        <div class="page-inner" data-section-id="catalog_lineup">
          <div class="h2">Featured Products</div>
          <table class="table">
            <tr>
              <th>No</th><th>Product</th><th>Category</th><th>Size</th><th>MOQ</th><th>Lead Time</th>
            </tr>
            ${displaySkus.map((sku, i) => `
              <tr>
                <td>${i + 1}</td>
                <td><strong>${sku.productName}</strong></td>
                <td>${sku.category || '-'}</td>
                <td>${sku.sizeMlG ? `${sku.sizeMlG}ml` : '-'}</td>
                <td>${sku.moq || workspace.defaultMoq || 500}</td>
                <td>${sku.leadTime || workspace.defaultLeadTime || 20} days</td>
              </tr>
            `).join('')}
          </table>
          
          <div class="callout" style="margin-top:20px">
            <strong>Pricing</strong>: Contact us for volume-based pricing. All prices negotiable based on order quantity.
          </div>
        </div>
        ${renderFooter(workspace.companyName, 2)}
      </section>
  `;

  // Individual SKU pages
  displaySkus.forEach((sku, index) => {
    html += `
      <!-- Page ${index + 3}: SKU ${index + 1} -->
      <section class="page" data-page="${index + 3}" ${index >= 4 ? 'data-include="detailed"' : ''}>
        ${renderHeader(`Product ${index + 1}`, sku.category || 'Skincare', '', dateStr)}
        <div class="page-inner" data-section-id="catalog_sku_${sku.id}">
          <div class="grid-2">
            <div>
              <div class="h1" style="font-size:24px">${sku.productName}</div>
              <p class="small">SKU: ${sku.sku}</p>
              
              <div class="hr"></div>
              
              <table class="table">
                <tr><th>Category</th><td>${sku.category || '-'}</td></tr>
                <tr><th>Size</th><td>${sku.sizeMlG ? `${sku.sizeMlG}ml/g` : '-'}</td></tr>
                <tr><th>HS Code</th><td>${sku.hsCode || 'TBD'}</td></tr>
                <tr><th>MOQ</th><td>${sku.moq || workspace.defaultMoq || 500} units</td></tr>
                <tr><th>Lead Time</th><td>${sku.leadTime || workspace.defaultLeadTime || 20} days</td></tr>
              </table>
            </div>
            <div class="card" style="background:#f7faff;display:flex;align-items:center;justify-content:center;min-height:250px">
              <p class="small">Product Image</p>
            </div>
          </div>
          
          <div class="hr"></div>
          
          <div class="card">
            <div class="h3">Key Benefits</div>
            <p class="p">${sku.claims?.join(' · ') || 'Premium Korean skincare formulation'}</p>
          </div>
          
          ${sku.ingredients?.length ? `
            <div class="card" style="margin-top:10px">
              <div class="h3">Key Ingredients</div>
              <p class="small">${sku.ingredients.slice(0, 5).join(', ')}</p>
            </div>
          ` : ''}
        </div>
        ${renderFooter(workspace.companyName, index + 3)}
      </section>
    `;
  });

  // Last page: FAQ (detailed mode)
  if (mode === 'detailed') {
    html += `
      <!-- FAQ Page -->
      <section class="page" data-page="${displaySkus.length + 3}" data-include="detailed">
        ${renderHeader('FAQ & Policies', 'Common Questions', '', dateStr)}
        <div class="page-inner" data-section-id="catalog_faq">
          <div class="h2">Frequently Asked Questions</div>
          
          <div class="card" style="margin-bottom:10px">
            <div class="h3">Sample Policy</div>
            <p class="p">Sample sets available for qualified buyers. Minimum order commitment may be required.</p>
          </div>
          
          <div class="card" style="margin-bottom:10px">
            <div class="h3">OEM/ODM Services</div>
            <p class="p">Custom formulation and private label services available. Contact us for details.</p>
          </div>
          
          <div class="card" style="margin-bottom:10px">
            <div class="h3">Shipping & Logistics</div>
            <p class="p">We support FOB, CIF, and DDP terms. Typical shipping time 7-14 days depending on destination.</p>
          </div>
          
          <div class="hr"></div>
          
          <div class="callout">
            <strong>Ready to Order?</strong><br/>
            Contact: ${workspace.contactEmail || 'sales@company.com'}<br/>
            ${workspace.contactPhone || '+82-2-XXX-XXXX'}
          </div>
        </div>
        ${renderFooter(workspace.companyName, displaySkus.length + 3)}
      </section>
    `;
  }

  html += '</div>';
  return html;
}

// ==================== Compliance Snapshot 템플릿 ====================
function renderCompliance(data: DocumentTemplateData, mode: DocumentMode): string {
  const { workspace, project, skus, rulepack } = data;
  const dateStr = data.date || format(new Date(), 'yyyy-MM-dd');
  const countries = project.countries;

  let html = `
    <style>${DOCUMENT_CSS}</style>
    <div class="doc-wrap">
      <!-- Page 1: Overview -->
      <section class="page" data-page="1">
        ${renderHeader('Export Readiness Snapshot', 'Compliance Check (Draft)', '', dateStr, `Target: ${countries.join(', ')}`)}
        <div class="page-inner">
          ${renderDraftBanner()}
          
          <div class="callout warn" data-section-id="compliance_disclaimer">
            <strong>주의</strong><br/>
            본 문서는 MVP 데모용 샘플 RulePack 기반입니다. 정확한 최신 규정은 추후 업데이트됩니다.
            법적 '확정 판정'이 아닌 "준비 신호(가능/주의/추가확인)"를 제공합니다.
          </div>

          <div class="h2">Target Markets</div>
          <div class="kpi">
            ${countries.map(country => `
              <div class="card">
                <div class="label">${country}</div>
                <div class="val badge warn" style="font-size:12px">주의 필요</div>
              </div>
            `).join('')}
          </div>

          <div class="hr"></div>

          <div class="h2">Products Checked</div>
          <table class="table" data-section-id="compliance_products">
            <tr><th>Product</th><th>SKU</th><th>Status</th></tr>
            ${skus.slice(0, 5).map(sku => `
              <tr>
                <td>${sku.productName}</td>
                <td>${sku.sku}</td>
                <td><span class="badge warn">확인 필요</span></td>
              </tr>
            `).join('')}
          </table>
        </div>
        ${renderFooter(workspace.companyName, 1)}
      </section>

      <!-- Page 2: Checklist -->
      <section class="page" data-page="2">
        ${renderHeader('Compliance Checklist', 'What to Prepare', '', dateStr)}
        <div class="page-inner" data-section-id="compliance_checklist">
          <div class="h2">Required Documents & Actions</div>
          
          <div class="card" style="margin-bottom:10px">
            <div class="h3">✓ Label Compliance</div>
            <p class="p">Ensure all required label elements are present for target markets.</p>
            <p class="small" style="margin-top:8px">
              ${rulepack?.labelMust?.join(' · ') || 'INCI, Net Content, Manufacturer Info, Warnings'}
            </p>
          </div>

          <div class="card" style="margin-bottom:10px">
            <div class="h3">✓ Ingredient Review</div>
            <p class="p">Check for restricted/banned ingredients in target markets.</p>
            <p class="small" style="margin-top:8px">
              Sample red flags: ${rulepack?.ingredientsRedFlagExample?.join(', ') || 'Varies by market'}
            </p>
          </div>

          <div class="card" style="margin-bottom:10px">
            <div class="h3">✓ Registration Requirements</div>
            <p class="p">${rulepack?.focus?.join('. ') || 'Check local registration requirements.'}</p>
          </div>

          <div class="callout" style="margin-top:20px">
            <strong>Watchouts</strong><br/>
            ${rulepack?.watchouts?.map(w => `• ${w}`).join('<br/>') || '• Check local regulations before export'}
          </div>
        </div>
        ${renderFooter(workspace.companyName, 2)}
      </section>

      <!-- Page 3: Action Items -->
      <section class="page" data-page="3">
        ${renderHeader('Next Steps', 'Action Required', '', dateStr)}
        <div class="page-inner" data-section-id="compliance_actions">
          <div class="h2">Top 5 Actions</div>
          
          <table class="table">
            <tr><th>#</th><th>Action</th><th>Priority</th><th>Status</th></tr>
            <tr><td>1</td><td>Confirm ingredient list with OCR/manual check</td><td>High</td><td><span class="badge warn">Pending</span></td></tr>
            <tr><td>2</td><td>Review label design for target market</td><td>High</td><td><span class="badge">Not Started</span></td></tr>
            <tr><td>3</td><td>Gather certifications (CGMP, ISO, etc.)</td><td>Medium</td><td><span class="badge">Not Started</span></td></tr>
            <tr><td>4</td><td>Check claims for compliance</td><td>Medium</td><td><span class="badge">Not Started</span></td></tr>
            <tr><td>5</td><td>Confirm HS codes</td><td>Low</td><td><span class="badge">Not Started</span></td></tr>
          </table>

          <div class="hr"></div>

          <div class="callout">
            <strong>RulePack Version</strong><br/>
            ${rulepack?.version || 'MVP Sample RulePack v0.3'}<br/>
            <span class="small">This is a sample ruleset for demonstration. Verify with official sources.</span>
          </div>
        </div>
        ${renderFooter(workspace.companyName, 3)}
      </section>
  `;

  // Detailed mode: Pages 4-6
  if (mode === 'detailed') {
    html += `
      <!-- Page 4: Market Details -->
      <section class="page" data-page="4" data-include="detailed">
        ${renderHeader('Market Requirements', 'By Country', '', dateStr)}
        <div class="page-inner" data-section-id="compliance_markets">
          ${countries.map(country => `
            <div class="card" style="margin-bottom:14px">
              <div class="h2">${country}</div>
              <table class="table">
                <tr><th>Focus Areas</th><td>Registration, Labeling, Ingredients</td></tr>
                <tr><th>Label Must</th><td>INCI, Net Content, Manufacturer, Warnings</td></tr>
                <tr><th>Special Notes</th><td>Check specific category requirements</td></tr>
              </table>
            </div>
          `).join('')}
        </div>
        ${renderFooter(workspace.companyName, 4)}
      </section>

      <!-- Page 5: Risk Assessment -->
      <section class="page" data-page="5" data-include="detailed">
        ${renderHeader('Risk Assessment', 'Potential Issues', '', dateStr)}
        <div class="page-inner" data-section-id="compliance_risks">
          <div class="h2">Risk Matrix</div>
          <table class="table">
            <tr><th>Risk</th><th>Likelihood</th><th>Impact</th><th>Mitigation</th></tr>
            <tr>
              <td>Ingredient restriction</td>
              <td><span class="badge warn">Medium</span></td>
              <td>High</td>
              <td>Pre-screen with RulePack</td>
            </tr>
            <tr>
              <td>Label non-compliance</td>
              <td><span class="badge warn">Medium</span></td>
              <td>Medium</td>
              <td>Use template labels</td>
            </tr>
            <tr>
              <td>Registration delay</td>
              <td><span class="badge">Low</span></td>
              <td>Medium</td>
              <td>Start early, use local agent</td>
            </tr>
          </table>
        </div>
        ${renderFooter(workspace.companyName, 5)}
      </section>

      <!-- Page 6: Summary -->
      <section class="page" data-page="6" data-include="detailed">
        ${renderHeader('Summary', 'Export Readiness Score', '', dateStr)}
        <div class="page-inner" data-section-id="compliance_summary" style="text-align:center;padding-top:80px">
          <div class="h1" style="font-size:48px;color:var(--warn)">65%</div>
          <p class="p" style="margin-top:10px">Export Readiness Score (Estimated)</p>
          
          <div class="kpi" style="margin-top:40px">
            <div class="card">
              <div class="label">Documents</div>
              <div class="val badge warn">Incomplete</div>
            </div>
            <div class="card">
              <div class="label">Ingredients</div>
              <div class="val badge warn">Review Needed</div>
            </div>
            <div class="card">
              <div class="label">Labels</div>
              <div class="val badge">Not Checked</div>
            </div>
          </div>

          <div class="callout" style="margin-top:40px;text-align:left">
            <strong>Next Steps</strong><br/>
            1. Complete ingredient confirmation<br/>
            2. Review label requirements<br/>
            3. Prepare buyer package
          </div>
        </div>
        ${renderFooter(workspace.companyName, 6)}
      </section>
    `;
  }

  html += '</div>';
  return html;
}

// ==================== 메인 렌더링 함수 ====================
export function renderDocument(
  type: DocumentType,
  mode: DocumentMode,
  data: DocumentTemplateData
): string {
  switch (type) {
    case 'brand_deck':
      return renderBrandDeck(data, mode);
    case 'catalog':
      return renderCatalog(data, mode);
    case 'compliance':
      return renderCompliance(data, mode);
    case 'pi':
      return renderPI(data as PITemplateData, mode);
    case 'contract':
      return renderContract(data as ContractTemplateData, mode);
    default:
      return `<div>Unknown document type: ${type}</div>`;
  }
}

// ==================== 템플릿 키 기반 렌더링 함수 ====================
// Maps template keys from useDocumentRunner to document types
export function renderDocumentByKey(
  templateKey: string,
  presetKey: string
): string {
  // Create mock data for demo
  const mockWorkspace = {
    companyName: 'K-Beauty Co., Ltd.',
    brandName: 'GLOWLAB',
    address: '123 Gangnam-daero, Gangnam-gu, Seoul, Korea',
    contactEmail: 'export@glowlab.co.kr',
    contactPhone: '+82-2-1234-5678',
    bankName: 'Shinhan Bank',
    bankAccountNo: '123-456-789012',
    bankSwift: 'SHBKKRSE',
    bankAccountName: 'K-Beauty Co., Ltd.',
  };

  const mockProject: ProjectData = {
    countries: ['US', 'JP', 'EU'],
    channel: 'wholesale',
    buyerType: 'distributor',
    tradeStage: presetKey,
    currency: 'USD',
    language: 'en',
  };

  const mockBuyer: BuyerData = {
    companyName: 'Global Beauty Inc.',
    country: 'US',
    contactName: 'John Smith',
    contactEmail: 'buyer@globalbeauty.com',
    address: '123 Main St, New York, NY 10001, USA',
  };

  const mockSKUs: SKUData[] = [
    {
      id: 'sku-1',
      no: 1,
      sku: 'GL-SRM-001',
      productName: 'Hydra Glow Serum',
      spec: '30ml',
      category: 'Skincare',
      hsCode: '3304.99',
      qty: 1000,
      unitPrice: 9.5,
      amount: 9500,
    },
    {
      id: 'sku-2',
      no: 2,
      sku: 'GL-TNR-002',
      productName: 'Cica Calm Toner',
      spec: '200ml',
      category: 'Skincare',
      hsCode: '3304.99',
      qty: 500,
      unitPrice: 7.0,
      amount: 3500,
    },
    {
      id: 'sku-3',
      no: 3,
      sku: 'GL-CRM-003',
      productName: 'Barrier Repair Cream',
      spec: '50ml',
      category: 'Skincare',
      hsCode: '3304.99',
      qty: 800,
      unitPrice: 11.5,
      amount: 9200,
    },
  ];

  const mockTrade: TradeData = {
    currency: 'USD',
    incoterms: 'FOB Incheon',
    paymentTerms: 'T/T 30% deposit, 70% before shipment',
    leadTime: '21-28 days',
    moq: 500,
    validityDays: 14,
  };

  const mockData: DocumentTemplateData = {
    workspace: mockWorkspace,
    project: mockProject,
    skus: mockSKUs,
    buyer: mockBuyer,
    trade: mockTrade,
  };

  // Map template keys to document types
  const keyToType: Record<string, DocumentType> = {
    'DECK_COMPANY_BRAND_15P': 'brand_deck',
    'CATALOG_PRODUCTS_15P': 'catalog',
    'COMPLIANCE_SNAPSHOT_15P': 'compliance',
    'DOC_PI': 'pi',
    'DOC_SAMPLE_PI': 'pi',
    'DOC_CONTRACT': 'contract',
  };

  const docType = keyToType[templateKey];
  
  if (docType) {
    // Use detailed mode for main documents, summary for sample PI
    const mode: DocumentMode = templateKey === 'DOC_SAMPLE_PI' ? 'summary' : 'detailed';
    return renderDocument(docType, mode, mockData);
  }

  // Return placeholder for unimplemented templates
  return renderPlaceholder(templateKey, mockWorkspace);
}

// Placeholder for unimplemented templates
function renderPlaceholder(templateKey: string, workspace: { companyName: string; brandName?: string }): string {
  const templateNames: Record<string, { name: string; nameKr: string }> = {
    'BUYER_OUTREACH_MESSAGE': { name: 'Buyer Outreach Message', nameKr: '바이어 메시지' },
    'DOC_PACKING_LIST_SIMPLE': { name: 'Sample Packing List', nameKr: '샘플 포장명세서' },
    'DOC_SHIPPING_NOTE': { name: 'Shipping Note', nameKr: '발송 안내문' },
    'DOC_LABEL_DRAFT': { name: 'Label Draft', nameKr: '라벨 초안' },
    'DOC_MSDS_SUMMARY': { name: 'MSDS/Ingredients Summary', nameKr: 'MSDS/성분 요약' },
    'DOC_COMMERCIAL_INVOICE': { name: 'Commercial Invoice', nameKr: '상업 송장' },
    'DOC_PACKING_LIST': { name: 'Packing List', nameKr: '포장명세서' },
    'DOC_LABEL_FINAL': { name: 'Label Final', nameKr: '최종 라벨' },
    'DOC_CROSSCHECK_REPORT': { name: 'Cross-document Check', nameKr: '실수 체크 리포트' },
  };

  const template = templateNames[templateKey] || { name: templateKey, nameKr: '' };
  const dateStr = format(new Date(), 'yyyy-MM-dd');

  return `
    <style>${DOCUMENT_CSS}</style>
    <div class="doc-wrap">
      <section class="page" data-page="1">
        <div class="header">
          <div class="brandmark">
            <div class="logo"></div>
            <div>
              <div class="doctitle">${template.name}</div>
              <div class="small">${template.nameKr}</div>
            </div>
          </div>
          <div class="docmeta">${dateStr}</div>
        </div>
        <div class="page-inner">
          <div class="draft-banner">⚠️ 이 문서는 <strong>협상/검토용 초안</strong>입니다.</div>
          
          <h1 class="h1">${template.nameKr || template.name}</h1>
          <p class="p">${workspace.brandName || workspace.companyName}</p>
          
          <div class="callout" style="margin-top:40px;">
            <strong>Coming Soon</strong><br/>
            이 템플릿은 현재 개발 중입니다.<br/>
            곧 실제 내용이 생성됩니다.
          </div>
        </div>
        <div class="footer">
          <span>${workspace.brandName || workspace.companyName}</span>
          <span>Page 1 / 1</span>
        </div>
      </section>
    </div>
  `;
}

// 문서 섹션 추출
export function extractSections(html: string): { id: string; content: string }[] {
  const sections: { id: string; content: string }[] = [];
  const regex = /data-section-id="([^"]+)"[^>]*>([\s\S]*?)(?=<\/div>|<\/section>|<\/table>)/g;
  let match;
  
  while ((match = regex.exec(html)) !== null) {
    sections.push({
      id: match[1],
      content: match[2].trim()
    });
  }
  
  return sections;
}

// 섹션 업데이트
export function updateSection(html: string, sectionId: string, newContent: string): string {
  const regex = new RegExp(
    `(data-section-id="${sectionId}"[^>]*>)[\\s\\S]*?(?=<\\/div>|<\\/section>)`,
    'g'
  );
  return html.replace(regex, `$1${newContent}`);
}
